[general]
live_config_reload = true
ipc_socket = false

[window]
opacity = 1
# padding = { x = 700 }

[colors]
draw_bold_text_with_bright_colors = true
primary.background = "#060200"

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
normal.family = "BigBlueTerm437 Nerd Font"
normal.style = "Bold"
size = 9

[mouse]
hide_when_typing = true
