confirm-before-quit = false

[window]
blur = false
colorspace = "display-p3"

[renderer]
performance = "high"
disable_unfocused_render = true
level = 1
filters = ["/home/admin/.config/rio/slang-shaders/crt/newpixie-mini.slangp"]
